# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: EOS add-on
version: "1.0.1"
slug: eos
description: Energy Optimization System add-on
url: "https://github.com/Duetting/ha_eos_addon/tree/main/eos"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
  - config:rw
ports:
  8503/tcp: 8503
ports_description:
  8503/tcp: EOS fastapi server
# options:
# schema:
backup_exclude:
  - /data/eos/cache
image: "ghcr.io/Duetting/{arch}-addon-eos"
